options:
  # Don't merge default rules
  merge-default-rules: true
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# File Options
files:
  include: 'src/styles/*.s+(a|c)ss'
  ignore:
    - 'node_modules/**/*.s+(a|c)ss'
rules:
  no-color-keywords: 0